name: GH Pages
on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Install
      run: npm ci

    - name: Build
      run: npm run pages

    - name: Deploy gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: dist
