name: NPM Check Updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  npm-check-updates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npx ncu --upgrade --doctor --reject react-router-dom,@types/react-router-dom,@types/node
    - run: npx ncu --upgrade --doctor --target minor
    - run: npx ncu --upgrade --doctor --target patch
    - uses: EndBug/add-and-commit@v7
