name: NPM Publish
on:
    workflow_dispatch:
jobs:
    npm-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - name: npm version minor
              run: |
                  TAG=$(npm version minor --no-git-tag-version)
                  echo "TAG=$(echo $TAG)" >> $GITHUB_ENV
            - run: npm ci
            - run: npm run build
            - uses: EndBug/add-and-commit@v7
              with:
                  default_author: github_actions
                  message: Release $TAG
                  tag: $TAG
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
