name: NPM Publish
on:
    workflow_dispatch:
jobs:
    npm-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - run: |
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config user.name "github-actions"
                  npm version minor
            - run: npm ci
            - run: npm run build
            - uses: EndBug/add-and-commit@v7
              with:
                  default_author: github_actions
                  message: Upgraded package dependencies
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
