name: NPM Check Updates
on:
    workflow_dispatch:
    schedule:
        - cron: '0 16 * * *'
jobs:
    npm-check-updates:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npm i -g npm-check-updates
            - run: ncu -x $SKIP || ncu --doctor -u -x $SKIP
              env:
                  SKIP: react-router-dom,@types/react-router-dom,@types/node
            - run: ncu -t minor || ncu --doctor -u -t minor
            - run: ncu -t patch || ncu --doctor -u -t patch
            - uses: EndBug/add-and-commit@v7
              with:
                  default_author: github_actions
                  message: Upgraded package dependencies
